[package]
name = "sov"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
duckdb = "0.9.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
thiserror = "1.0.57"
walkdir = "2.5.0"
